[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
authors = [
    { name = "alcristo" },
    { name = "pnarvaez" }
]
description = "Maze Generator"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.md" }
dependencies = [
    "numpy"
]

[tool.setuptools]
py-modules = ["maze_generator"]
